name: release-acr

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "${VERSION}" == "${BRANCH_NAME}" ]]; then
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::testnotation.azurecr.io/integration:${VERSION}
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: testnotation.azurecr.io
          username: testnotation
          password: ${{ secrets.TEST_NOTATION }}
      - name: docker build
        run: |          
          docker build . -t ${{ steps.prepare.outputs.ref }}
          docker push ${{ steps.prepare.outputs.ref }}
      - name: akv login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: setup notation
        uses: shizhMSFT/setup-notation@main
        with:
          version: v1.0.0-rc.7
          # Override the download url
          # TODO: add checksum
          url: https://github.com/Two-Hearts/notation/releases/download/v1.0.0-rc.7-pluginInstall/notation_1.0.0-rc.7-pluginInstall_linux_amd64.tar.gz
      - name: install notation plugin
        run: |
          notation plugin install --name azure-kv testnotation.azurecr.io/akv-plugin-linux:v1
          notation plugin ls
      - name: sign released image
        env:
          AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
          AZURE_CLIENT_ID: 40421dc0-256b-4501-a65f-7ae18ce999d5
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          notation key add --plugin azure-kv --id "https://testnotationakv.vault.azure.net/keys/testNotationPEM/ea55efedc6eb4928b5294e7b172061e0" --default testKey
          notation sign ${{ steps.prepare.outputs.ref }}