name: release-acr

on:
  push:
    tags:
      - v*

env:
  ACR_TO_RELEASE: testnotation.azurecr.io
  ACR_REPO_TO_RELEASE: integration
  ACR_USERNAME: testnotation
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "${VERSION}" == "${BRANCH_NAME}" ]]; then
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::${{ env.ACR_TO_RELEASE }}/${{ env.ACR_REPO_TO_RELEASE }}:${VERSION}
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_TO_RELEASE }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - name: docker build release
        run: |          
          docker build -t ${{ steps.prepare.outputs.ref }} .
          docker push ${{ steps.prepare.outputs.ref }}
      - name: akv login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: setup akv permissions  
      #   run: |
      #     az account set -s ${{ env.AKV_SUBSCRIPTION_ID }}
      #     az keyvault set-policy -n ${{ env.AKV_NAME }} --secret-permissions get list --key-permissions sign --certificate-permissions get --spn ${{ env.AZURE_SERVICE_PRINCIPLE_CLIENT_ID }}
      - name: setup notation
        uses: shizhMSFT/setup-notation@main
        with:
          version: v1.0.0-rc.7
          # Override the download url
          # TODO: add checksum
          url: https://github.com/Two-Hearts/notation/releases/download/v1.0.0-rc.7-pluginInstall/notation_1.0.0-rc.7-pluginInstall_linux_amd64.tar.gz
      - name: sign releasd image using key pair from AKV
        uses: Two-Hearts/notation-azure-kv-sign-actions@main
        env:
          AKV_PLUGIN_REF: testnotation.azurecr.io/akv-plugin-linux@sha256:ee0b6ccbb6f4232e908c7a6876c10e56f5a02dff4537c30a38690fef1430a61b
          AKV_NAME: testnotationAKV
          AZURE_SERVICE_PRINCIPLE_CLIENT_ID: 40421dc0-256b-4501-a65f-7ae18ce999d5
          AKV_SUBSCRIPTION_ID: dfb63c8c-7c89-4ef8-af13-75c1d873c895
          AKV_KEYID: https://testnotationakv.vault.azure.net/keys/testNotationPEM/ea55efedc6eb4928b5294e7b172061e0
          NOTATION_EXPERIMENTAL: 1
        with:
          key_id: ${{ env.AKV_KEYID }}
          target_artifact_reference: ${{ steps.prepare.outputs.ref }}
      
      # - name: verify image
      #   uses: notaryproject/notation-actions/verify
      #   with:
      #     target_ref: ${{ steps.prepare.outputs.ref }}
      #     trust_policy: .github/notation/trustpolicy.json
      #     trust_store: .github/notation/truststore/
          